---
galaxy_info:
  role_name: aem_license
  author: Max Barrass
  description: Install license to an AEM Instance.
  company: aem.design
  issue_tracker_url: https://github.com/aem-design/ansible-role-aem-license/issues
  license: Apache 2.0
  min_ansible_version: 2.4

  platforms:
    - name: Ubuntu
      versions:
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - aem
    - cms
    - web
    - aemdesign
    - license
